version: "3.8"

services:
  redis:
    image: redis:8.0-M02-alpine3.20
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_DATABASE: crack_spectra
      MYSQL_ROOT_PASSWORD: yourpassword
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "13306:3306"
    restart: always

volumes:
  mariadb_data:
