port = 8082
debug = true
workspace = "/home/user/rainy/workspace/CrackSpectra"

[database]
mysql_user = "root"
mysql_password = "yourpassword"
mysql_host = "localhost"
mysql_port = "3306"
mysql_db = "crack_spectra"

[k8s]
namespace = "experiment"

[redis]
host = "localhost:6379"

[system]
timezone = "Asia/Shanghai"