port = 8082
debug = true
workspace = "/home/user/rainy/workspace/CrackSpectra"

[database]
mysql_user = "root"
mysql_password = "yourpassword"
mysql_host = "127.0.0.1"
mysql_port = "13306"
mysql_db = "crack_spectra"

[k8s]
namespace = "crack-spectra-job"

[redis]
host = "127.0.0.1:6379"

[system]
timezone = "Asia/Shanghai"