port = 8082
debug = true

[system]
timezone = "Asia/Shanghai"

[database]
mysql_user = "root"
mysql_password = "yourpassword"
mysql_host = "localhost"
mysql_port = "3306"
mysql_db = "crack-spectra"

[redis]
host = "localhost:6379"

[k8s]
namespace = "crack-spectra"